require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'

target 'App' do
  capacitor_pods
  # Adicionando o RevenueCat via CocoaPods para compatibilidade total com Appflow
  pod 'RevenueCat', '5.59.2'
end
